name: Auto Commit Updates
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "Auto Commit Bot"
          git config user.email "bot@chatgpt.local"

      - name: Stage all changes
        run: git add .

      - name: Commit if changed
        run: |
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-update from generator"
      
      - name: Push changes
        run: git push
