name: Generate Layers
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Pillow
        run: pip install pillow

      - name: Run generator
        run: |
          python generator/generate_layers.py

      - name: Upload generated image
        uses: actions/upload-artifact@v4
        with:
          name: layered_preview
          path: output/layered_preview.png
